
package frc.robot.constants;

import static edu.wpi.first.units.Units.*;

import org.ironmaple.simulation.drivesims.COTS;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.*;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.*;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.*;

import frc.robot.subsystems.Swerve;
import frc.util.dataTypes.Triplet;
import frc.util.dataTypes.Tuple;
import frc.util.simulation.SwerveSim;


// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class DriveConstants {
    public static final LinearVelocity MaxSpeed = OasisTunerConstants.kSpeedAt12Volts;
    public static final AngularVelocity MaxAngularRate = RotationsPerSecond.of(0.75);
    public static final Distance RobotWidth = Inches.of(30);
    public static final double COF = COTS.WHEELS.VEX_GRIP_V2.cof;

    public static final Time kSimLoopPeriod = Seconds.of(0.005); // faster than default for better accuracy
    @SuppressWarnings("unchecked")
    public static final SwerveSim getSwerveSim(Swerve drivetrain) {
        return new SwerveSim(
            new Triplet<Time, Mass, Double>(kSimLoopPeriod, AutonomousConstants.ROBOT_MASS, COF),
            new Tuple<Distance, Distance>(RobotWidth, RobotWidth),
            new Tuple<DCMotor, DCMotor>(DCMotor.getKrakenX60Foc(1),
            RobotMap.IS_OASIS ? DCMotor.getFalcon500Foc(1) : DCMotor.getKrakenX60Foc(1)), //TODO: change to 44 once wpilib 2026
            drivetrain.getModuleLocations(),
            drivetrain.getPigeon2(),
            drivetrain.getModules(),
            OasisTunerConstants.FrontLeft,
            OasisTunerConstants.FrontRight,
            OasisTunerConstants.BackLeft,
            OasisTunerConstants.BackRight);
    }
}
