
package frc.robot.constants;

import static edu.wpi.first.units.Units.*;

import org.ironmaple.simulation.drivesims.COTS;

import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.swerve.*;

import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.*;

import frc.robot.subsystems.Swerve;
import frc.util.dataTypes.Triplet;
import frc.util.dataTypes.Tuple;
import frc.util.simulation.SwerveSim;


// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class DriveConstants {
    protected static final Distance kWheelRadius = RobotMap.IS_OASIS ? OasisTunerConstants.kWheelRadius : MirageTunerConstants.kWheelRadius;
    public static final LinearVelocity kSpeedAt12Volts = RobotMap.IS_OASIS ? OasisTunerConstants.kSpeedAt12Volts : MirageTunerConstants.kSpeedAt12Volts;
    protected static final double kDriveGearRatio = RobotMap.IS_OASIS ? OasisTunerConstants.kDriveGearRatio : MirageTunerConstants.kDriveGearRatio;

    private static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> frontLeftModule =
        RobotMap.IS_OASIS ? OasisTunerConstants.FrontLeft : MirageTunerConstants.FrontLeft;
    private static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> frontRightModule =
        RobotMap.IS_OASIS ? OasisTunerConstants.FrontRight : MirageTunerConstants.FrontRight;
    private static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> backLeftModule =
        RobotMap.IS_OASIS ? OasisTunerConstants.BackLeft : MirageTunerConstants.BackLeft;
    private static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> backRightModule =
        RobotMap.IS_OASIS ? OasisTunerConstants.BackRight : MirageTunerConstants.BackRight;

    public static final Swerve createDrivetrain() {
        return RobotMap.IS_OASIS ? OasisTunerConstants.createDrivetrain() : MirageTunerConstants.createDrivetrain();
    }

    public static final LinearVelocity MaxSpeed = kSpeedAt12Volts;
    public static final AngularVelocity MaxAngularRate = RotationsPerSecond.of(0.75);
    public static final Distance RobotWidth = Inches.of(30);
    public static final double COF = COTS.WHEELS.VEX_GRIP_V2.cof;

    public static final Time kSimLoopPeriod = Seconds.of(0.005); // faster than default for better accuracy
    @SuppressWarnings("unchecked")
    public static final SwerveSim getSwerveSim(Swerve drivetrain) {
        return new SwerveSim(
            new Triplet<Time, Mass, Double>(kSimLoopPeriod, AutonomousConstants.ROBOT_MASS, COF),
            new Tuple<Distance, Distance>(RobotWidth, RobotWidth),
            new Tuple<DCMotor, DCMotor>(DCMotor.getKrakenX60Foc(1),
            RobotMap.IS_OASIS ? DCMotor.getFalcon500Foc(1) : DCMotor.getKrakenX60Foc(1)), //TODO: change to 44 once wpilib 2026
            drivetrain.getModuleLocations(),
            drivetrain.getPigeon2(),
            drivetrain.getModules(),
            frontLeftModule,
            frontRightModule,
            backLeftModule,
            backRightModule);
    }

    public static final SwerveRequest.FieldCentric fieldCentricRequest = new SwerveRequest.FieldCentric();
    public static final SwerveRequest.RobotCentric robotCentricRequest = new SwerveRequest.RobotCentric();
    public static final SwerveRequest.SwerveDriveBrake brakeRequest = new SwerveRequest.SwerveDriveBrake();
    public static final SwerveRequest.ApplyRobotSpeeds autonRequest = new SwerveRequest.ApplyRobotSpeeds();
}
